server {
    listen 80 default_server;
    server_name _;
    root /var/www/html;
    index index.html;
    location / { try_files $uri $uri/ =404; }
    location /status/gim { proxy_pass http://127.0.0.1:8010/api/health; }
    location /status/gryd { proxy_pass http://127.0.0.1:8080/; }
}
